server:
  port: 8082
  servlet:
    context-path: /api/v1

redis:
  config: ./././config/singleNodeConfig.yaml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
    username: root
    password: 123

  jpa:
    show-sql: true
    open-in-view: true
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: update