server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee?createDatabaseIfNotExist=true
    username: root
    password: 123

  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true

